# syntax=docker/dockerfile:1

FROM docker.io/throwtheswitch/madsciencelab

USER root
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    curl python3 python3-venv git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# install platformio    
RUN curl -fsSL -o get-platformio.py https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py
RUN python3 get-platformio.py

ADD platformio.ini /root/
WORKDIR /root
RUN /root/.platformio/penv/bin/pio pkg install -e jenkins

WORKDIR /home/dev/project
