# syntax=docker/dockerfile:1

FROM docker.io/python:3.14-slim

WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install --no-install-recommends -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
    
RUN python3 -m pip install --no-cache-dir -U platformio

WORKDIR /home/dev/project

ENTRYPOINT ["pio"]

CMD ["run", "-e", "jenkins"]
