[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp_common]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf

lib_deps = https://github.com/joltwallet/esp_littlefs.git
           baracodadailyhealthtech/cJSON@^1.7.18
board_build.filesystem = littlefs
board_build.partitions = littlefs_partitions.csv

[env:esp32-s3-devkitc-1]
extends = env:esp_common
monitor_speed = 115200

board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
build_flags = -D'SSID = '${sysenv.WIFI_SSID} -D'PASSWD = '${sysenv.WIFI_PASSWD}

[env:calibration_at_ib]
extends = env:esp32-s3-devkitc-1
build_flags = -DCALIBRATION_AT_IB -D'SSID = '${sysenv.WIFI_SSID} -D'PASSWD = '${sysenv.WIFI_PASSWD}

[env:calibration_no_current]
extends = env:esp32-s3-devkitc-1
build_flags = -DCALIBRATION_NO_CURRENT -D'SSID = '${sysenv.WIFI_SSID} -D'PASSWD = '${sysenv.WIFI_PASSWD}

[env:test]
extends = env:esp32-s3-devkitc-1
build_flags = -DTEST

[env:jenkins]
extends = env:esp_common